In [40]:
!pip install plotly

Requirement already satisfied: plotly in c:\users\rosy n\appdata\local\anaconda3\lib\site-packages (6.3.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\rosy n\appdata\local\anaconda3\lib\site-packages (from plotly) (1.31.0)
Requirement already satisfied: packaging in c:\users\rosy n\appdata\local\anaconda3\lib\site-packages (from plotly) (24.2)

In [2]:
import pandas as pd

In [3]:
pd.read_csv('diabetes.csv')

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [4]:
df = pd.read_csv('diabetes.csv')

In [5]:
df.shape

(768, 9)

In [6]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [7]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [8]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [10]:
df['Pregnancies'].value_counts()

Pregnancies
1     135
0     111
2     103
3      75
4      68
5      57
6      50
7      45
8      38
9      28
10     24
11     11
13     10
12      9
14      2
17      1
15      1
Name: count, dtype: int64

In [11]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [12]:
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [13]:
import seaborn as sns
import matplotlib.pyplot as plt

In [14]:
df.head(1)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1

In [15]:
x=df.drop(columns=['Outcome'])
y=df['Outcome']

In [16]:
x.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33

In [17]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [18]:
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
import matplotlib.pyplot as plt
import numpy as np

In [19]:
x_train, x_test, y_train, y_test = train_test_split (x, y, test_size=0.2, random_state=10)

In [20]:
df.shape, x_train.shape, x_test.shape

((768, 9), (614, 8), (154, 8))

In [21]:
diabetes = svm.SVC(kernel='linear')  #rbf, #sigmoid, #poly

In [22]:
diabetes.fit(x_train, y_train)

SVC(kernel='linear')

In [23]:
xtrain_prediction = diabetes.predict(x_train)
training_data_accuracy = accuracy_score(xtrain_prediction, y_train)

In [24]:
print('Accuracy Score', training_data_accuracy)

Accuracy Score 0.7752442996742671

In [25]:
xtest_prediction = diabetes.predict(x_test)
testing_data_accuracy = accuracy_score(xtest_prediction, y_test)

In [26]:
print('Accuracy Score', testing_data_accuracy)

Accuracy Score 0.7597402597402597

In [27]:
df.to_csv('Cleaned Diabetes Dataset.csv') #to export to csv

In [28]:
import warnings
warnings.filterwarnings('ignore', category=UserWarning)

In [29]:
##the input_data holds your data values
input_data = (6,148,72,35,0,33.6,0.627,50)

# changing the input data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshaping the array
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# standardizing the input data
#std_data = scaler.transform(input_data_reshaped)
#print(std_data)

prediction = diabetes.predict(input_data_reshaped)
#print(prediction)

if (prediction[0] == 0):
  print('Congratulations! You are not susceptible to diabetes')

else:
  print('Unfortunately, you are susceptible to diabetes')

Unfortunately, you are susceptible to diabetes

In [30]:
6,148,72,35,0,33.6,0.627,50
1,85,66,29,0,26.6,0.351,31

(1, 85, 66, 29, 0, 26.6, 0.351, 31)

In [31]:
##the input_data holds your data values
input_data = (1,85,66,29,0,26.6,0.351,31)

# changing the input data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshaping the array
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# standardizing the input data
#std_data = scaler.transform(input_data_reshaped)
#print(std_data)

prediction = diabetes.predict(input_data_reshaped)
#print(prediction)

if (prediction[0] == 0):
  print('Congratulations! You are not susceptible to diabetes.')

else:
  print('Unfortunately, you are susceptible to diabetes.')

Congratulations! You are not susceptible to diabetes.

In [32]:
import pickle

In [33]:
# Converting our file to a pickle file
filename = 'diabetes_classifier.sav'

In [34]:
# Writing our pickle file
pickle.dump(diabetes, open('diabetes_classifier', 'wb'))

In [35]:
loaded_model = pickle.load(open('diabetes_classifier', 'rb'))

In [36]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [37]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [38]:
df.shape

(768, 9)

In [ ]:
# to check the error before deploying to streamlit, launch anaconda prompt and input the names of the folders
# cd desktop, cd python, cd ml, cd mlprojects then streamlit run app.py

In [ ]:
# to get the requirements.txt, on github, go to add file, then create new file